apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: integration-bigbelly

resources:
  - ../../base/

patchesJson6902:
  - target:
      group: batch
      version: v1
      kind: CronJob
      name: integration-bigbelly
    path: patches/image.yaml
