apiVersion: batch/v1
kind: CronJob
metadata:
  name: integration-bigbelly
spec:
  schedule: "0 * * * *" # run hourly by default
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers:
            - env:
                - name: POD_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
              name: integration-bigbelly
              image: ghcr.io/diwise/integration-bigbelly:changeme
              imagePullPolicy: IfNotPresent              
              resources:
                limits:
                  cpu: 100m
                  memory: 250Mi
                requests:
                  cpu: 50m
                  memory: 100Mi
          restartPolicy: Never
          serviceAccountName: integration-bigbelly
